version: '3.8'

networks:
  test-cli:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: cli-nginx
    ports:
      - 7005:7005
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
      - ./:/app
    networks:
      - test-cli
    depends_on:
      - php
  
  postgres:
    image: postgres:14-alpine3.15
    container_name: cli-postgres
    ports:
      - "5431:5432"
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      DB_DATABASE_TESTING: ${DB_DATABASE_TESTING}
    volumes:
      - ./docker/postgres/pg-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - test-cli

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cli-php
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DB_CONNECTION}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    volumes:
      - ./:/app
    networks:
      - test-cli

  composer:
    image: composer:latest
    container_name: cli-composer
    volumes:
      - ./:/app
    depends_on:
      - php
    networks:
      - test-cli
    command: install --ignore-platform-reqs --no-scripts